name: Actualizar Backend APIM

on:
  workflow_dispatch:
    inputs:
      producto:
        description: 'Servicio a actualizar'
        required: true
        type: choice
        options:
          - Modelo Dia
          - Salud
          - Danna Link
          - Emisión Viajes
          - eCommerce Autos
          - Vida Ley
          - Otro (Especificar abajo)
      producto_otro:
        description: 'Si seleccionaste "Otro", escribe el nombre exacto aquí (debe coincidir con el Excel)'
        required: false
        type: string
      tipo_red:
        description: 'Hacia dónde enrutar el tráfico'
        required: true
        type: choice
        options:
          - Expressroute
          - Internet

jobs:
  backup:
    name: 1. Backup de Políticas
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install requests

      - name: Login en Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Ejecutar Script de Backup
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_RG: 'rg-apim-dev'
          AZURE_APIM_NAME: 'apim-pacifico-dev'
          PRODUCTO: ${{ github.event.inputs.producto }}
          PRODUCTO_OTRO: ${{ github.event.inputs.producto_otro }}
        run: python scripts/backup_policies.py

      - name: Subir Backup a GitHub
        uses: actions/upload-artifact@v4
        with:
          name: backup-politicas-${{ github.event.inputs.producto }}
          path: backups/
          retention-days: 7

  update:
    name: 2. Actualizar APIM
    needs: backup # Esto asegura que este job no empiece hasta que el backup termine bien
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install requests

      - name: Descargar Backup previo
        uses: actions/download-artifact@v4
        with:
          name: backup-politicas-${{ github.event.inputs.producto }}
          path: backups/

      - name: Login en Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Ejecutar Script de Actualización
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_RG: 'rg-apim-dev'
          AZURE_APIM_NAME: 'apim-pacifico-dev'
          PRODUCTO: ${{ github.event.inputs.producto }}
          PRODUCTO_OTRO: ${{ github.event.inputs.producto_otro }}
          TIPO_RED: ${{ github.event.inputs.tipo_red }}
        run: python scripts/update_policies.py
